# Create service account 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  namespace: appstudio-grafana
---
# Create secret for the service account
apiVersion: v1
kind: Secret
metadata:
  name: metrics-reader
  namespace: appstudio-grafana
  annotations:
    kubernetes.io/service-account.name: metrics-reader
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-proxy
  namespace: appstudio-grafana
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-proxy
  namespace: appstudio-grafana
  annotations:
    kubernetes.io/service-account.name: grafana-proxy
type: kubernetes.io/service-account-token
---
# Create cluster role binding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-monitoring-view-grafana
subjects:
  - kind: ServiceAccount
    name: metrics-reader
    namespace: appstudio-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: appstudio-grafana
  name: grafana-proxy
rules:
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-proxy
  namespace: appstudio-grafana
roleRef:
  kind: ClusterRole
  name: grafana-proxy
subjects:
  - kind: ServiceAccount
    name: grafana-proxy
    namespace: appstudio-grafana
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: appstudio-grafana
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: ocp-injected-certs
---
# Create a Grafana instance
# Do not add security to this yaml
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: appstudio-grafana
  namespace: appstudio-grafana
spec:
  config:
    users:
      viewers_can_edit: true
    auth:
      disable_login_form: false
      disable_signout_menu: true
    auth.basic:
      enabled: true
    auth.proxy:
      enabled: true
      enable_login_token: true
      header_property: username
      header_name: X-Forwarded-User
    auth.anonymous:
      enabled: false    
    log:
      level: warn
      mode: console
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - appstudio-grafana
  containers:
    - args:
        - '-provider=openshift'
        - '-pass-basic-auth=false'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:3000'
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
        - '-cookie-secret-file=/etc/proxy/secrets/token'
        - '-openshift-service-account=grafana-proxy'
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-openshift-ca=/etc/grafana-configmaps/ocp-injected-certs/ca-bundle.crt'
        - '-skip-auth-regex=^/metrics'
      image: 'quay.io/openshift/origin-oauth-proxy@sha256:b6536bfcfaf30a6425d589facd672bae3245f933b2a7399bda3f12e393bd671b'
      name: grafana-proxy
      ports:
        - containerPort: 9091
          name: https
      resources: {}
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-grafana-tls
          readOnly: false
        - mountPath: /etc/proxy/secrets
          name: grafana-proxy
          readOnly: false
  secrets:
    - grafana-tls
    - grafana-proxy
  configMaps:
    - ocp-injected-certs
  service:
    ports:
      - name: https
        port: 9091
        protocol: TCP
        targetPort: https
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: grafana-tls
  ingress:
    enabled: false
    targetPort: https
    termination: reencrypt
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: grafana-tls
  client:
    preferService: True
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-access"}}'
  deployment:
    envFrom:
      - prefix: thanos
        secretRef:
          name: metrics-reader

---
# Add prometheus Datasource to Grafana
# Using the thanos-querier url for the datasource
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: prometheus-grafanadatasource
  namespace: appstudio-grafana
spec:
  name: prometheus-thanos-grafanadatasource.yaml
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer ${thanostoken}'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
