apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - https://github.com/konflux-ci/konflux-ci/konflux-ci/ui/core?ref=61a67ed1783f4129062d889ee67a76454454b6e5

configMapGenerator:
  - name: proxy-init-config
    behavior: replace
    literals:
      - IMPERSONATE=false
      - TEKTON_RESULTS_URL=https://tekton-results-api-service.tekton-results.svc.cluster.local:8080

patches:
  - path: add-service-certs-patch.yaml
    target:
      group: ""
      version: v1
      kind: Service
      name: proxy
  - path: oauth2-proxy-args-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: proxy
  - path: remove-run-as-user-proxy-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: proxy
  - path: set-replicas-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
  - path: set-hostname.yaml
    target:
      kind: Route
      version: v1

namespace: konflux-ui
