---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/avi-biton/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-grafana-dev
