---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/gbenhaim/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-tb
