apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../staging
  - ../../base/smee-client
  - ../../base/ui
  - ../../base/keycloak
patchesStrategicMerge:
  - delete-applications.yaml
