resources:
- allow-argocd-to-manage.yaml
- https://github.com/redhat-appstudio/image-controller/config/default?ref=ece26df1a3b509043cfc74da0f264611830fbf66

images:
- name: quay.io/redhat-appstudio/image-controller
  newName: quay.io/gbenhaim0/image-controller
  newTag: no-devfile

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

