apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pipeline-service
  namespace: appstudio-workload-monitoring
  labels:
    app: pipeline-metrics-exporter
    prometheus: appstudio-workload
spec:
  selector:
    matchLabels:
      app: pipeline-metrics-exporter
  endpoints:
    - path: /metrics
      port: metrics
      interval: 15s
      scheme: http
  namespaceSelector:
    matchNames:
      - openshift-pipelines
