apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/redhat-appstudio/build-service/config/default?ref=29b09e5d8350f75c92d5796fbbf62647fe28610b

namespace: build-service

images:
- name: quay.io/redhat-appstudio/build-service
  newName: quay.io/gbenhaim0/build-service
  newTag: config-webhook-with-scm-url

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true


configMapGenerator:
  - name: webhook-config
    files: 
      - webhook-config.json

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: image-expiration-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: pac-webhook-insecure-ssl-patch.yaml

components:
  - ../components/rh-certs
  - ../components/webhook-config
